name: Robot Framework Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Robot Framework tests
        uses: joonvena/robotframework-docker-action@v0.1
        with:
          BROWSER: chrome
          ROBOT_TEST_DIR: /robot_tests
          ROBOT_RESULTS_DIR: /reports

      - name: Upload test reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: /reports
