name: Robot Framework Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Robot Framework tests
        uses: joonvena/robotframework-docker-action@v0.1
        # with:
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/robot_tests
          # ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports

      - name: Adding markdown
        run: |
          echo '### Test Results' >> $GITHUB_STEP_SUMMARY
          pwd
          ls -la
          ls -la /opt/robotframework/reports/
          cat /opt/robotframework/reports/output.xml
          cat /opt/robotframework/reports/log.html
          cat /opt/robotframework/reports/report.html

      # - name: Upload test reports
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: reports
      #     path: /reports
